Repository SIEHP/siehp-api, pull requests merged in 2024-01, with the labels that each got.

#3 `[DEV][FEAT]` Create nest project;
  .eslintrc.js
  .gitignore
  .prettierrc
  README.md
  nest-cli.json
  package-lock.json
  package.json
  src/app.controller.spec.ts
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/main.ts
  test/app.e2e-spec.ts
  test/jest-e2e.json
  tsconfig.build.json
  tsconfig.json
Labels: documentation, enhancement

#2 `[MAIN][FEAT]` Create nest project;
  .eslintrc.js
  .gitignore
  .prettierrc
  README.md
  nest-cli.json
  package-lock.json
  package.json
  src/app.controller.spec.ts
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/main.ts
  test/app.e2e-spec.ts
  test/jest-e2e.json
  tsconfig.build.json
  tsconfig.json
Labels: documentation, enhancement

#5 `[DEV][FEAT]` Updated readme and add issue templates;
  README.md
  issue_template.md
  pull_request_template.md
Labels: documentation

#4 `[DEV][FEAT]` Updated readme and add issue templates;
  README.md
  issue_template.md
  pull_request_template.md
Labels: documentation

#6 `[DEV][FEAT]` CI/CD;
  .dockerignore
  .env
  .env.example
  .github/workflows/test-and-build-development.yaml
  .github/workflows/test-and-build-production.yaml
  Dockerfile
  Dockerfile-deploy
  cloudbuild.yaml
  docker-compose.yaml
  package.json
  src/main.ts
Labels: enhancement

#8 `[DEV][FIX]` Gcr domain name;
  cloudbuild.yaml
Labels: bug

#7 `[MAIN][FEAT]` CI/CD;
  .dockerignore
  .env
  .env.example
  .github/workflows/test-and-build-development.yaml
  .github/workflows/test-and-build-production.yaml
  Dockerfile
  Dockerfile-deploy
  cloudbuild.yaml
  docker-compose.yaml
  package.json
  src/main.ts
Labels: enhancement

#9 [DEV][FIX] DDD structure
  src/app.module.ts
  src/domain/classes/controllers/index.controller.ts
  src/domain/classes/services/index.service.ts
  src/domain/content/controllers/index.controller.ts
  src/domain/content/controllers/index.ts
  src/domain/content/services/index.service.ts
  src/domain/content/services/index.ts
  src/domain/exercises/controllers/index.controller.ts
  src/domain/exercises/controllers/index.ts
  src/domain/exercises/services/index.service.ts
  src/domain/exercises/services/index.ts
  src/domain/sheets/controllers/index.controller.ts
  src/domain/sheets/controllers/index.ts
  src/domain/sheets/services/index.service.ts
  src/domain/sheets/services/index.ts
  src/domain/user/controllers/index.controller.ts
  src/domain/user/controllers/index.ts
  src/domain/user/services/index.service.ts
  src/domain/user/services/index.ts
Labels: bug

#16 `[MERGE][DEV]`feat/database env variable
  .env
  .gitignore
Labels: bug, enhancement

#15 `[MERGE][MAIN]`Feat/database env variable
  .env
  .gitignore
Labels: bug, enhancement

#13 `[MERGE][DEV]`feat/refactor architecture
  src/constants/index.ts
  src/modules/classes/dto/index.ts
  src/modules/classes/infra/http/controllers/index.ts
  src/modules/classes/infra/http/middlewares/index.ts
  src/modules/classes/infra/http/routes/index.ts
  src/modules/classes/repositories/index.ts
  src/modules/classes/services/index.ts
  src/modules/content/dto/index.ts
  src/modules/content/infra/http/controllers/index.ts
  src/modules/content/infra/http/middlewares/index.ts
  src/modules/content/infra/http/routes/index.ts
  src/modules/content/repositories/index.ts
  src/modules/content/services/index.ts
  src/modules/image/dto/index.ts
  src/modules/image/infra/http/controllers/index.ts
  src/modules/image/infra/http/middlewares/index.ts
  src/modules/image/infra/http/routes/index.ts
  src/modules/image/repositories/index.ts
  src/modules/image/services/index.ts
  src/modules/log/dto/index.ts
  src/modules/log/infra/http/controllers/index.ts
  src/modules/log/infra/http/middlewares/index.ts
  src/modules/log/infra/http/routes/index.ts
  src/modules/log/repositories/index.ts
  src/modules/log/services/index.ts
  src/modules/security/dto/index.ts
  src/modules/security/infra/http/controllers/index.ts
  src/modules/security/infra/http/middlewares/index.ts
  src/modules/security/infra/http/routes/index.ts
  src/modules/security/repositories/index.ts
  src/modules/security/services/index.ts
  src/modules/tag/dto/index.ts
  src/modules/tag/infra/http/controllers/index.ts
  src/modules/tag/infra/http/middlewares/index.ts
  src/modules/tag/infra/http/routes/index.ts
  src/modules/tag/repositories/index.ts
  src/modules/tag/services/index.ts
  src/modules/task/dto/index.ts
  src/modules/task/infra/http/controllers/index.ts
  src/modules/task/infra/http/middlewares/index.ts
  src/modules/task/infra/http/routes/index.ts
  src/modules/task/repositories/index.ts
  src/modules/task/services/index.ts
  src/modules/user/dto/index.ts
  src/modules/user/infra/http/controllers/index.ts
  src/modules/user/infra/http/middlewares/index.ts
  src/modules/user/infra/http/routes/index.ts
  src/modules/user/repositories/index.ts
  src/modules/user/services/index.ts
  src/shared/container/providers/index.ts
  src/shared/infra/http/routes/index.ts
Labels: enhancement

#14 `[MERGE][MAIN]`feat/refactored_directory_architecture
  src/constants/index.ts
  src/modules/classes/dto/index.ts
  src/modules/classes/infra/http/controllers/index.ts
  src/modules/classes/infra/http/middlewares/index.ts
  src/modules/classes/infra/http/routes/index.ts
  src/modules/classes/repositories/index.ts
  src/modules/classes/services/index.ts
  src/modules/content/dto/index.ts
  src/modules/content/infra/http/controllers/index.ts
  src/modules/content/infra/http/middlewares/index.ts
  src/modules/content/infra/http/routes/index.ts
  src/modules/content/repositories/index.ts
  src/modules/content/services/index.ts
  src/modules/image/dto/index.ts
  src/modules/image/infra/http/controllers/index.ts
  src/modules/image/infra/http/middlewares/index.ts
  src/modules/image/infra/http/routes/index.ts
  src/modules/image/repositories/index.ts
  src/modules/image/services/index.ts
  src/modules/log/dto/index.ts
  src/modules/log/infra/http/controllers/index.ts
  src/modules/log/infra/http/middlewares/index.ts
  src/modules/log/infra/http/routes/index.ts
  src/modules/log/repositories/index.ts
  src/modules/log/services/index.ts
  src/modules/security/dto/index.ts
  src/modules/security/infra/http/controllers/index.ts
  src/modules/security/infra/http/middlewares/index.ts
  src/modules/security/infra/http/routes/index.ts
  src/modules/security/repositories/index.ts
  src/modules/security/services/index.ts
  src/modules/tag/dto/index.ts
  src/modules/tag/infra/http/controllers/index.ts
  src/modules/tag/infra/http/middlewares/index.ts
  src/modules/tag/infra/http/routes/index.ts
  src/modules/tag/repositories/index.ts
  src/modules/tag/services/index.ts
  src/modules/task/dto/index.ts
  src/modules/task/infra/http/controllers/index.ts
  src/modules/task/infra/http/middlewares/index.ts
  src/modules/task/infra/http/routes/index.ts
  src/modules/task/repositories/index.ts
  src/modules/task/services/index.ts
  src/modules/user/dto/index.ts
  src/modules/user/infra/http/controllers/index.ts
  src/modules/user/infra/http/middlewares/index.ts
  src/modules/user/infra/http/routes/index.ts
  src/modules/user/repositories/index.ts
  src/modules/user/services/index.ts
  src/shared/container/providers/index.ts
  src/shared/infra/http/routes/index.ts
Labels: enhancement
